services:
  - type: web
    name: trainee-tracker
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn trainee_tracker.wsgi:application"
    plan: free
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11
      - key: DJANGO_DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: trainee-tracker-db
          property: connectionString

databases:
  - name: trainee-tracker-db
    plan: free
